test review exercise

diff --git a/.github/workflows/review-exercises.yaml b/.github/workflows/review-exercises.yaml
--- a/.github/workflows/review-exercises.yaml
+++ b/.github/workflows/review-exercises.yaml
@@ -92,6 +92,11 @@ jobs:
           IMAGE=devopsacademyau/reviewer:${{ steps.check.outputs.exercise }}-${{ steps.check.outputs.version }}
           echo ${{ github.workspace }}
           ls ${{ github.workspace }}
-          docker run -v ${{ github.workspace }}/${{ env.STUDENTS_FOLDER }}/${{ github.actor}}/exercises/${{ steps.check.outputs.exercise }}/:/exercise \
-            $IMAGE
-          docker ps -a
+          STATUS=$(docker run -v ${{ github.workspace }}/${{ env.STUDENTS_FOLDER }}/${{ github.actor}}/exercises/${{ steps.check.outputs.exercise }}/:/exercise \
+            $IMAGE)
+          if [ $STATUS = "fail" ];then
+            echo "::error title='Wrong answer'::'Secret file still exists. Please update your code and submit again.'";
+            exit 1;
+          fi;
+          echo "Secret file not found. Well done cleaning all your secrets."
+
